---
- name: Include dependencies
  ansible.builtin.include_tasks: dependencies.yml
  tags: [install]

- name: Include opencanary
  ansible.builtin.include_tasks: opencanary.yml
  tags: [install, update]
