---

- name: Start opencanaryd
  ansible.builtin.systemd:
    name: opencanaryd
    state: restarted

- name: Stop opencanaryd
  ansible.builtin.systemd:
    name: opencanaryd
    state: stopped

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslogd
    state: restarted

- name: Restart opencanaryd
  ansible.builtin.service:
    name: opencanaryd
    state: restarted
